// Contains structures for storing information about certificates
// and a function for reading a json file.
package main

import (
	"encoding/json"
	"io/ioutil"
)

type DomainInfo struct {
	Main string `json:"main"`
}

type CertificateRecord struct {
	Cert   string     `json:"certificate"`
	Key    string     `json:"key"`
	Domain DomainInfo `json:"domain"`
}

type CertProvider struct {
	Certificates []CertificateRecord
}

type AcmeJsonFile = map[string]CertProvider

// Reads the specified file generated by traefic
func ParseAcmeJsonFile(filepath string) (AcmeJsonFile, error) {
	// Read file
	content, err := ioutil.ReadFile(filepath)
	if err != nil {
		return nil, err
	}

	// Parse json
	var payload AcmeJsonFile
	err = json.Unmarshal(content, &payload)
	if err != nil {
		return nil, err
	}
	return payload, nil
}
